import type { Metadata } from 'next';
import './globals.css';
import { pretendard } from '@/utils/font';
import QueryProvider from '@/lib/tanstack/QueryProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable} font-pretendard`}>
      <body>
        <main className="mobile-container">
          <QueryProvider>{children}</QueryProvider>
        </main>
      </body>
    </html>
  );
}
